# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25, verbose_name='\u7528\u6237')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServerHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=16, verbose_name='IP')),
                ('user', models.CharField(max_length=25, verbose_name='\u7528\u6237')),
                ('password', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
                ('tags', models.CharField(max_length=100, verbose_name='\u6807\u7b7e')),
                ('location', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
                ('iskeys', models.BooleanField(verbose_name='\u5bc6\u94a5\u767b\u5f55')),
                ('ispub', models.BooleanField(verbose_name='\u5224\u65ad\u516c\u7f51')),
                ('sshfilename', models.CharField(max_length=100, verbose_name='\u5bc6\u94a5\u6587\u4ef6\u8def\u5f84')),
            ],
        ),
        migrations.AddField(
            model_name='mysqlinfo',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webask.ServerHost'),
        ),
    ]
