# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlinfo',
            name='tags',
            field=models.CharField(default=1, max_length=100, verbose_name='\u6807\u7b7e'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serverhost',
            name='ispub',
            field=models.BooleanField(verbose_name='\u516c\u7f51\u4e3b\u673a'),
        ),
    ]
